---
#System Settings
php_modules: [ 'php-curl', 'php-gd', 'php-mbstring', 'php-xml', 'php-xmlrpc', 'php-soap', 'php-intl', 'php-zip' ]

#MySQL Settings
mysql_root_password: "PASSW0RD"
mysql_db: "bukan_wordpress"
mysql_user: "ramadoni"
mysql_password: "PASSW0RD"

#HTTP Settings
http_host: "ansibledemo.local"
http_conf: "ansibledemo.local.conf"
http_port: "80"
